// components/Navbar/SearchBar.jsx
import React, { useRef } from "react";
import { MagnifyingGlassIcon, XCircleIcon } from "@heroicons/react/24/outline";
// import Form from "../Form";

export default function SearchBar({ className }) {
  const ref = useRef();
  return (
    <form
      action="https://www.google.com/search"
      method="get"
      className={`hidden lg:flex relative  justify-start items-center border rounded-full px-2 py-2 bg-gray-50 group focus-within:border-gray-700 ${className} transition-all`}
      ref={ref}
      target="_blank"
    >
      <div className="block absolute w-6 h-6 bg-transparent">
        <MagnifyingGlassIcon className="" />
      </div>

      <input type="hidden" name="q" value="site:axum.rs" />
      <input
        type="text"
        placeholder="输入关键字，按回车进行搜索"
        name="q"
        className="block  ml-7 w-full outline-none bg-transparent focus:mr-6 transition-all"
        onKeyUp={(e) => {
          if (e.key === "Enter") {
            ref.current.submit();
          }
        }}
      />
      {/* <button
        type="button"
        className="hidden absolute  right-2 w-5 h-5 overflow-hidden text-xs group-focus-within:block text-gray-500"
        onClick={() => {
          setKeyword("");
        }}
      >
        <XCircleIcon />
      </button> */}
    </form>
  );
}

// components/Header/SearchBar.vue
<script setup lang="ts">
const keyword = ref("");
const handleSearch = (e: Event) => {
  if (!keyword.value) {
    e.preventDefault();
    return false;
  }
  return true;
};
</script>

<template>
  <form
    class="col-span-6 flex flex-col w-full items-center"
    action="https://www.google.com/search"
    method="get"
    target="_blank"
    autocomplete="off"
    @submit="handleSearch"
  >
    <input type="hidden" name="q" value="site:axum.rs" />
    <div
      class="flex justify-start items-center gap-x-2 border rounded-full w-11/12 px-3 py-1.5 border-gray-200 text-gray-500 transition-all duration-300 focus-within:border-gray-300 focus-within:text-gray-600 focus-within:w-full focus-within:shadow-inner"
    >
      <Icon name="uil:search" class="shrink-0" size="1.25rem" />

      <input
        class="outline-none bg-transparent block w-full grow"
        type="text"
        name="q"
        v-model="keyword"
        placeholder="输入关键字，按回车进行搜索"
      />

      <button
        class="flex justify-center items-center flex-col h-full shrink-0"
        type="button"
        v-if="keyword"
        @click="keyword = ''"
      >
        <Icon name="uil:times" />
      </button>
    </div>
  </form>
</template>
