// components/MainMenu/Item.tsx
"use client";
import Link from "next/link";
import React from "react";

export default function Item({
  children,
  href = "",
  icon = <></>,
  isRelative = false,
  isGroup = false,
  isWidest = false,
  ext = <></>,
  isButton = false,
}: ChildrenProps & {
  href?: string;
  icon?: React.ReactNode;
  isRelative?: boolean;
  isGroup?: boolean;
  isWidest?: boolean;
  ext?: React.ReactNode;
  isButton?: boolean;
}) {
  return (
    <li
      className={`px-6 py-2 text-gray-800 hover:bg-gray-200/70 ${
        isRelative ? "relative" : ""
      } ${isGroup ? "group" : ""}`}
    >
      <_Item href={href} isButton={isButton}>
        <span className="w-6 h-6">{icon}</span>
        <span
          className={`text-lg font-normal ${
            isWidest ? "tracking-widest" : ""
          } xl:tracking-widest`}
        >
          {children}
        </span>
      </_Item>
      {ext}
    </li>
  );
}

function _Item({
  children,
  className = "",
  isButton = false,
  href = "",
  onClick = () => {},
}: ComponentProps & {
  isButton?: boolean;
  href?: string;
  onClick?: () => void;
}) {
  const css = `flex justify-start items-center space-x-3 ${className}`;
  if (isButton) {
    return (
      <button type="button" onClick={onClick} className={css}>
        {children}
      </button>
    );
  }

  return (
    <Link href={href} className={css} onClick={() => {}}>
      {children}
    </Link>
  );
}

// components/AsideMenu/Item.vue
<script setup lang="ts">
import { NuxtLink } from "#components";
defineProps<{ icon: string; href?: string }>();
const { $asideMenu } = use$status();

const emits = defineEmits(["click"]);
</script>

<template>
  <li
    class="w-full"
    @click="
      () => {
        $asideMenu = false;
        emits('click');
      }
    "
  >
    <component
      :is="href ? NuxtLink : 'button'"
      :to="href"
      class="flex justify-start items-center text-lg gap-x-3 font-normal w-full pl-10 py-2 hover:bg-gray-100 lg:px-8"
    >
      <Icon :name="icon" class="" size="1.45rem" />

      <div>
        <slot></slot>
      </div>
    </component>
  </li>
</template>
