// components/Loading.vue
<script setup lang="ts"></script>

<template>
  <Mask class="bg-transparent z-[999]">
    <div
      class="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 bg-black/70 p-6 rounded-md shadow-md flex flex-col justify-center items-center text-white w-36"
    >
      <Icon name="mdi:loading" class="animate-spin" size="3rem" />
    </div>
  </Mask>
</template>

// components/Loading.jsx
import React from "react";

export default function Loading({ children = "正在载入" }) {
  return (
    <div className="absolute inset-0 bg-gray-500/70 z-50 flex flex-col items-center justify-center  ">
      <span className="bg-orange-600 text-white px-3 py-2 border border-orange-700 rounded shadow">
        {children}
      </span>
    </div>
  );
}
