// pages/user/changepwd.jsx
import React, { useState } from "react";
import PageMeta from "../../components/PageMeta";
import PageTitle from "../../components/PageTitle";
import Card from "../../components/Card";
import Toast, { ToastDefaultOption } from "../../components/Toast";
// import Loading from "../../components/Loading";
import Form from "../../components/Form";
import { posta } from "../../fetcher/fetcher";
import { useRouter } from "next/router";

const defaultInputData = {
  new_password: "",
  re_password: "",
  password: "",
};
export default function UserChangePassword() {
  const [input, setInput] = useState({ ...defaultInputData });
  const [toast, setToast] = useState({ ...ToastDefaultOption });
  const [isSubmiting, setSubmiting] = useState(false);
  const router = useRouter();

  const onChangeHandler = (key) => (e) => {
    const v = e.target.value;
    setInput({ ...input, [key]: v });
  };

  const submitHanlder = async () => {
    try {
      if (input.new_password.length < 6) {
        setToast({ type: "error", msg: "新密码至少需要6个字符" });
        return;
      }
      if (input.re_password !== input.new_password) {
        setToast({ type: "error", msg: "两次输入的密码不一致" });
        return;
      }
      if (input.password.length < 6) {
        setToast({ type: "error", msg: "当前密码至少需要6个字符" });
        return;
      }
      if (input.password === input.new_password) {
        setToast({ type: "error", msg: "玩呢？改一样的密码" });
        return;
      }
      setSubmiting(true);
      const res = await posta("/user/change-pwd", { ...input });
      if (res?.code === 0) {
        setToast({ type: "success", msg: "恭喜，密码修改成功" });
        setInput({ ...defaultInputData });
        return;
      }
      if (res?.code === 9527) {
        router.push(`/login?r=/user/changepwd`);
        return;
      }
      if (res?.code === 9528) {
        setToast({ type: "error", msg: "表单输入有误，请检查你的输入" });
        return;
      }
      if (res?.code === 9529) {
        setToast({ type: "error", msg: "你输入的当前密码错误" });
        return;
      }
      if (res?.code !== 0) {
        setToast({ type: "error", msg: "操作失败，请检查你的网络" });
        return;
      }
    } catch (e) {
      console.log(e);
      setToast({ type: "error", msg: "操作失败，请检查你的网络" });
    } finally {
      setSubmiting(false);
    }
  };
  return (
    <>
      <PageMeta>修改密码</PageMeta>
      <PageTitle>修改密码</PageTitle>

      {toast.msg && (
        <Toast
          type={toast.type}
          callback={() => {
            setToast({ ...toast, msg: "" });
          }}
        >
          {toast.msg}
        </Toast>
      )}

      <Card className="mx-3 lg:mx-0">
        <div className="relative p-3">
          <Form
            className="grid grid-cols-1 gap-6"
            isLoading={isSubmiting}
            onSubmit={submitHanlder}
          >
            <label className="block">
              <span className="text-gray-700 before:text-red-600 before:content-['*'] before:mr-1 before:text-sm">
                新密码
              </span>
              <input
                type="password"
                className="
                    form-input
                    mt-0
                    block
                    w-full
                    px-0.5
                    border-0 border-b-2 border-gray-200
                    focus:ring-0 focus:border-black
                  "
                placeholder="输入新密码"
                required
                onChange={onChangeHandler("new_password")}
                value={input.new_password}
              />
            </label>

            <label className="block">
              <span className="text-gray-700 before:text-red-600 before:content-['*'] before:mr-1 before:text-sm">
                重复新密码
              </span>
              <input
                type="password"
                className="
                    form-input
                    mt-0
                    block
                    w-full
                    px-0.5
                    border-0 border-b-2 border-gray-200
                    focus:ring-0 focus:border-black
                  "
                placeholder="再次输入新密码"
                required
                onChange={onChangeHandler("re_password")}
                value={input.re_password}
              />
            </label>

            <label className="block">
              <span className="text-gray-700 before:text-red-600 before:content-['*'] before:mr-1 before:text-sm">
                当前密码
              </span>
              <input
                type="password"
                className="
                    form-input
                    mt-0
                    block
                    w-full
                    px-0.5
                    border-0 border-b-2 border-gray-200
                    focus:ring-0 focus:border-black
                  "
                placeholder="输入当前使用的密码"
                required
                onChange={onChangeHandler("password")}
                value={input.password}
              />
            </label>

            <div
              className="mt-0
                    w-full
                    px-0.5
                    flex justify-end items-start space-x-3"
            >
              <button
                type="submit"
                className="bg-blue-500 px-6 py-2 border  rounded text-white border-blue-600 hover:bg-blue-600 inline-block"
              >
                提交
              </button>
              <button
                type="reset"
                className="bg-white px-6 py-2 border  rounded text-gray-600 border-gray-400 hover:bg-gray-100 inline-block"
                onClick={() => {
                  setInput({ ...defaultInputData });
                }}
              >
                重置
              </button>
            </div>
          </Form>
        </div>
      </Card>
    </>
  );
}

// pages/user/change-pwd.vue
<script setup lang="ts">
const frm = reactive({
  password: "",
  new_password: "",
  re_password: "",
});

const { $toast, $msg, $isLoading } = use$status();
const { $put } = use$fetch();
const { $user } = use$auth();

const passwordValidator = (p: string, msgPrefix: string) => {
  if (!p.trim()) {
    throw new Error(`${msgPrefix}不能为空`);
  }
  if (p.trim().length < 6) {
    throw new Error(`${msgPrefix}至少6位`);
  }
};
const handleSubmit = async () => {
  try {
    passwordValidator(frm.password, "现用密码");
    passwordValidator(frm.new_password, "新密码");
    passwordValidator(frm.re_password, "确认密码");
    if (frm.password === frm.new_password) {
      throw new Error("新密码不能和现用密码相同");
    }
    if (frm.new_password !== frm.re_password) {
      throw new Error("两次输入的密码不一致");
    }
    await $put("/user/user/password", { ...frm }, () => {
      $msg.value = "密码修改成功";
      $isLoading.value = false;
      return navigateTo("/user/logout") as void;
    });
  } catch (e) {
    if (e instanceof Error) {
      $toast.value = e.message;
    } else if (typeof e === "string") {
      $toast.value = e;
    } else {
      $toast.value = `${e}`;
    }
  }
};
</script>

<template>
  <PageTitle icon="heroicons:key" title="修改密码" />
  <form
    class="my-6 bg-white rounded-md p-6 space-y-4"
    autocomplete="off"
    @submit.prevent="handleSubmit"
    v-if="$user"
  >
    <div class="flex flex-col gap-y-2 cursor-default">
      <div>用户</div>
      <div class="border rounded px-3 py-2 text-gray-500 bg-gray-100">
        {{ $user.email }} ({{ $user.nickname }})
      </div>
    </div>

    <label class="flex flex-col gap-y-2">
      <div>现用密码</div>
      <div class="border rounded px-3 py-2 focus-within:ring-1">
        <input
          type="password"
          class="block w-full outline-none"
          required
          v-model="frm.password"
        />
      </div>
      <div class="text-gray-400 text-xs">
        输入你现在使用的密码，以验证你的身份。
      </div>
    </label>
    <label class="flex flex-col gap-y-2">
      <div>新密码</div>
      <div class="border rounded px-3 py-2 focus-within:ring-1">
        <input
          type="password"
          class="block w-full outline-none"
          required
          v-model="frm.new_password"
        />
      </div>
      <div class="text-gray-400 text-xs">输入6个字符以上的新密码。</div>
    </label>
    <label class="flex flex-col gap-y-2">
      <div>重复密码</div>
      <div class="border rounded px-3 py-2 focus-within:ring-1">
        <input
          type="password"
          class="block w-full outline-none"
          required
          v-model="frm.re_password"
        />
      </div>
      <div class="text-gray-400 text-xs">再次输入你新密码。</div>
    </label>

    <div class="flex justify-end">
      <button
        type="submit"
        class="border rounded-md px-3 py-1.5 bg-blue-600 text-white lg:hover:bg-blue-500"
      >
        提交
      </button>
    </div>
  </form>
</template>
