// pages/subscribe.jsx
import React from "react";
import PageMeta from "../components/PageMeta";
import PageTitle from "../components/PageTitle";
import Card from "../components/Card";
import Link from "next/link";

export default function Subscribe() {
  return (
    <>
      <PageMeta>订阅</PageMeta>
      <PageTitle>订阅</PageTitle>

      <Card className="mx-3 mb-3 lg:mx-0">
        <div className="">
          <ul className="grid grid-cols-4 text-lg">
            <li className="font-semibold">权益</li>
            <li className="font-semibold">游客</li>
            <li className="font-semibold">普通用户</li>
            <li className="font-semibold text-orange-600">订阅用户</li>
          </ul>
          <ul className="grid grid-cols-4 my-1">
            <li></li>
            <li></li>
            <li className="font-semibold">$0/月</li>
            <li className="font-semibold">$1/月</li>
          </ul>
          <ul className="grid grid-cols-4 py-3">
            <li></li>
            <li></li>
            <li>
              <Link
                className="px-3 py-1 border hover:border-gray-300 hover:bg-gray-50"
                href="/register"
              >
                注册
              </Link>
            </li>
            <li>
              <Link
                className="px-3 py-1  bg-orange-500 text-white hover:bg-orange-600 lg:font-normal lg:py-2"
                href=""
              >
                订阅
              </Link>
            </li>
          </ul>
          <ul className="grid grid-cols-4 border-y py-3">
            <li>人机验证</li>
            <li>HCaptcha 人机验证</li>
            <li>HCaptcha 人机验证</li>
            <li>可关闭人机验证</li>
          </ul>
          <ul className="grid grid-cols-4 border-b py-3">
            <li>多设备登录</li>
            <li>N/A</li>
            <li>只能在一个设备上登录</li>
            <li>最多可在三个设备上登录</li>
          </ul>
          <ul className="grid grid-cols-4 border-b py-3">
            <li>在线时长</li>
            <li>N/A</li>
            <li>强制每次在线20分钟</li>
            <li>最长可设置在线2小时(120分钟)</li>
          </ul>
          <ul className="grid grid-cols-4 border-b py-3">
            <li>付费专题</li>
            <li>不可查看</li>
            <li>购买后可查看</li>
            <li>特定收费专题免费查看；购买教程时享受折扣</li>
          </ul>
          <ul className="grid grid-cols-4 border-b py-3">
            <li>学习记录</li>
            <li>N/A</li>
            <li>可回顾最后5条学习记录</li>
            <li>可回顾所有学习记录</li>
          </ul>
          <ul className="grid grid-cols-4 border-b py-3">
            <li>积分</li>
            <li>N/A</li>
            <li>签到获取积分，积分可以用于兑换收费专题</li>
            <li>
              每次购买订阅赠送等比例积分、签到获取积分，积分可以用于兑换收费专题
            </li>
          </ul>
          <ul className="grid grid-cols-4 border-b py-3">
            <li>投稿</li>
            <li>N/A</li>
            <li>可进行投稿，稿件一旦接纳将获取积分奖励</li>
            <li>可进行投稿，稿件一旦接纳将获取积分奖励</li>
          </ul>
          <ul className="grid grid-cols-4 border-b py-3">
            <li>请求教程</li>
            <li>N/A</li>
            <li>可请求教程，每次消耗一定量的积分</li>
            <li>请求教程消耗的积分减半</li>
          </ul>

          <div className="my-3 text-gray-600 text-sm">
            *
            某些权益可能在当前版本中并未实现，我们将通过不断的版本迭代实现更多的权益。
          </div>
        </div>
      </Card>
    </>
  );
}

// pages/subscribe.vue
<script setup lang="ts"></script>

<template>
  <PageTitle icon="heroicons:building-storefront" title="订阅" />

  <ul
    class="flex flex-col-reverse justify-between lg:items-end mx-auto gap-y-4 lg:gap-y-0 lg:gap-x-4 lg:flex-row my-6 text-center 2xl:my-12 2xl:gap-x-6"
  >
    <li
      class="border bg-gradient-to-bl from-gray-100 to-gray-200 rounded-lg shadow-md p-4 space-y-1 lg:space-y-2 lg:w-1/3 hover:bg-gradient-to-br"
    >
      <div class="text-lg font-semibold lg:text-xl xl:text-2xl">游客</div>
      <div>HCaptcha 人机验证</div>
      <div>无需登录</div>
      <div>无在线时长</div>
      <div>不可查看付费专题</div>
      <div>无学习记录</div>
      <div>无积分</div>
      <div>不可投稿</div>
      <div>不可请求教程</div>
    </li>
    <li
      class="border bg-gradient-to-bl from-cyan-500 to-cyan-600 text-gray-100 rounded-lg shadow-md p-4 space-y-1 lg:space-y-2 lg:w-1/3 hover:bg-gradient-to-br"
    >
      <div class="text-lg font-semibold lg:text-xl xl:text-2xl">注册用户</div>
      <div>Turnstile 人机验证</div>
      <div>只能在一个设备上登录</div>
      <div>强制每次在线20分钟</div>
      <div>购买后可查看付费专题</div>
      <div>可回顾最后5条学习记录</div>
      <div>签到获取积分，积分可以用于兑换收费专题</div>
      <div>可进行投稿，稿件一旦接纳将获取积分奖励</div>
      <div>可请求教程，每次消耗一定量的积分</div>
      <div class="flex justify-center items-center gap-x-2 py-3">
        <div>
          <NuxtLink
            class="border bg-gray-200 px-1.5 py-0.5 lg:px-2.5 lg:py-1 text-gray-900"
            to="/register"
          >
            免费注册
          </NuxtLink>
        </div>
      </div>
    </li>
    <li
      class="border bg-gradient-to-bl from-cyan-600 to-cyan-800 text-gray-100 rounded-lg shadow-md p-4 space-y-1 lg:space-y-2 lg:w-1/3 hover:bg-gradient-to-br"
    >
      <div class="text-lg font-semibold lg:text-xl xl:text-2xl mb-3">
        订阅用户
      </div>
      <div>可关闭人机验证</div>
      <div>最多可在三个设备上登录</div>
      <div>最长可设置在线2小时</div>
      <div>特定收费专题免费查看；购买教程时享受折扣</div>
      <div>可回顾所有学习记录</div>
      <div>
        每次购买订阅赠送等比例积分、签到获取积分，积分可以用于兑换收费专题
      </div>
      <div>可进行投稿，稿件一旦接纳将获取积分奖励</div>
      <div>请求教程消耗的积分减半</div>
      <div class="flex justify-center items-center gap-x-2 py-3">
        <div
          class="flex justify-start items-center gap-x-1 bg-teal-100 border text-gray-900 px-1.5 py-0.5 text-sm lg:px-2.5 lg:py-1"
        >
          <img src="/usdt.svg" class="w-4 object-cover" />
          <span>1</span>
          <span>/30天</span>
        </div>
        <div>
          <button
            class="border bg-orange-600 text-white px-1.5 py-0.5 lg:px-2.5 lg:py-1"
          >
            订阅
          </button>
        </div>
      </div>
    </li>
  </ul>
</template>
